iot_dashboard:
  mqtt:
    hostname: "localhost"
  hue:
    bridge: "xxx"
    refresh_intervall: 2
  umbrella_detection:
    model_dir: "ssd_v3"
  weather_api:
    api_key: "xxx"
    location: "Thalwil, Switzerland"
  flower:
    mac_address: "xxx"
    refresh_intervall: 10
